<div class="row contentBlock-top">
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php include('aboutIndiacomSidePanel.php'); ?>
        <?php include('importantdatesPanel.php'); ?>
    </div>
    <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12">
        <span class="h1 text-theme">Review Process, Publication and Indexing</span>
        <hr>
        <div class="row text-justify body-text">
            <div class="col-md-12">
                <p>
                    <strong>
                        <span class="text-theme h3">Plagiarism Policy:</span>
                    </strong>
                    <br>
                    Please note that the papers having plagiarism level above 10% will not be accepted for INDIACom-2015. The INDIACom team will be checking plagiarism level of all the submitted papers for ensuring the originality of content using Turnitin. Hence, authors are advised in their own interest, to use a tool like Turnitin, iThenticate, Viper, PlagScan etc. to check the plagiarism level of their manuscripts before submission. The originality report generated by the tool, may also be submitted at the time of paper submission.
                </p>
                <p>
                    The conference aims at carrying out two rounds of review process. In the first round, the papers submitted by the authors will be assessed on the basis of their technical suitability, scope of work and plagiarism. The corresponding authors of qualifying submissions will be intimated for their papers to be double blind reviewed by three experts on the basis of originality, novelty, clarity, completeness, relevance, significance and research contribution. Final decision regarding acceptance of papers will be based upon the review remarks received after the second round of the review process.
                </p>
                <p>
                    The shortlisted papers will be accepted for presentation and inclusion in the conference proceedings, having <strong>ISSN 0973 &ndash; 7529 </strong>and <strong>ISBN 978-93-80544-14-4</strong> serials.  Conference proceedings will also be available in the form of CD-ROMs. Upon acceptance, authors will be required to <strong>register and present their papers.
                </p>
                <p>
                    Please note that <span class="text-theme">papers will be published in the conference proceedings, bearing the above mentioned ISSN and ISBN serials, only if at least one of the authors is officially registered in advance by 22<sup>nd</sup> January, 2015 and he/she undertakes to present the paper.</span>
                </p>

            </div>
        </div>
    </div>
</div>
