<div class="row contentBlock-top">
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php include('aboutIndiacomSidePanel.php'); ?>
        <?php include('importantdatesPanel.php'); ?>
    </div>
    <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12">
        <span class="h1 text-theme">Review Process, Publication and Indexing</span>
        <hr>
        <div class="row text-justify body-text">
            <div class="col-md-12">
                <p>
                    <strong>
                        <span class="text-theme h3">Plagiarism Policy:</span>
                    </strong>
                    <br/>
                    <strong>
						Please note that plagiarised papers will not be accepted for INDIACom-2016. The INDIACom team will be checking plagiarism level of all the submitted papers for ensuring the originality of content using Turnitin. Hence, authors are advised in their own interest, to use a tool like Turnitin, iThenticate, Viper, PlagScan etc. to check the plagiarism level of their manuscripts before submission. The originality report generated by the tool, may also be submitted at the time of paper submission. 
					</strong>
                </p>
                <p>
                    The conference aims at carrying out two rounds of review process. In the first round, the papers submitted by the authors will be assessed on the basis of their technical suitability, scope of work and plagiarism. The corresponding authors of qualifying submissions will be intimated for their papers to be double blind reviewed by three experts on the basis of originality, novelty, clarity, completeness, relevance, significance and research contribution. Final decision regarding acceptance of papers will be based upon the review remarks received after the second round of the review process.
                </p>
                <p>
                    The shortlisted papers of all the tracks (Track 1 - Track 5) will be accepted for presentation and publication in the Soft Copy of Conference proceedings, bearing <strong>ISBN serial 978-93-80544-20-5</strong>, in the form of DVDs. <span class = "text-danger">Accepted Papers of Regular Sessions (Track 1 - Track 4) will also be published in the Hard Copy of Conference Proceedings having <strong>ISSN 0973–7529</strong> and <strong>ISBN 978-93-80544-19-9</strong> serials</span>. Upon acceptance, authors will be required to <strong>register and present their papers.</strong>
                </p>
                <p>
                    Please note that <strong><span class = "text-danger">papers will be published in the conference proceedings, bearing the above mentioned ISSN and ISBN serials, only if at least one of the authors is officially registered in advance (as specified in <a href = "importantDates">important dates</a>) and he/she undertakes to present the paper.</span></strong>
                </p>
				<p>
					<strong>INDIACom-2016</strong> is approved by <strong>IEEE's Conference Publication Program (IEEE CPP)</strong>. This means that the Conference proceedings of accepted papers (for oral presentations), <strong>which will be presented in the conference</strong>, will be submitted to <strong><span class = "text-danger">IEEE Xplore</span></strong>, which is indexed with world’s leading <strong>Abstracting & Indexing (A&I)</strong> databases, including <strong><span class = "text-danger">ISI, SCOPUS, DBLP, EI-Compendex,</span></strong> etc.
				</p>

				<h2 class="text-theme">IEEE Xplore Catalog Number for the Proceedings</h2>
                <table class="table table-bordered table-responsive table-striped">
                    <tr>
                        <th>Media Type</th>
                        <th>Part Number</th>
                        <th>ISBN</th>
                    </tr>
                    <tr>
                        <td>IEEE Xplore Compliant</td>
                        <td>CFP1683W-ART</td>
                        <td>978-93-80544-21-2</td>
                    </tr>
                    <tr>
                        <td>DVD</td>
                        <td>CFP1683W-DVD</td>
                        <td>978-93-80544-20-5</td>
                    </tr>
                    <tr>
                        <td>PRINT</td>
                        <td>CFP1683W-PRT</td>
                        <td>978-93-80544-19-9</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
